import React, { useState, useEffect } from 'react';
import { useAuthStore } from '../../lib/auth';
import { api } from '../../lib/api';

interface Vendor {
  id: string;
  businessName: string;
  description: string;
}

export default function HomePage() {
  const { user } = useAuthStore();
  const [vendors, setVendors] = useState<Vendor[]>([]);
  const [message, setMessage] = useState('');

  useEffect(() => {
    // Only fetch vendors if user is logged in
    if (user) {
      api.get('/vendors').then(res => setVendors(res.data)).catch(console.error);
    }
  }, [user]);

  const testBooking = async () => {
    try {
      // Create a mock vendor first to ensure we have one to book
      const vendorRes = await api.post('/vendors', {
        businessName: 'Mock Test Vendor',
        category: 'Test',
        description: 'Autogenerated vendor for testing booking',
        basePrice: 100,
        city: 'Test City',
      });
      
      // In a real app we need admin approval, but for Deliverable 1 let's just make the booking against it directly
      await api.post('/bookings', {
        vendorId: vendorRes.data.id,
        startTime: new Date().toISOString(),
        endTime: new Date(Date.now() + 3600000).toISOString(),
      });

      setMessage('Vendor profile created and test booking sent! Vendor owner received a notification.');
    } catch (err: any) {
      setMessage(err.response?.data?.message || 'Failed test booking');
    }
  };

  return (
    <div className="space-y-6">
      {/* Top row: Analytics & Metrics */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 glass-panel p-6">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold text-white">Analytics Overview</h2>
            <div className="bg-white/5 border border-white/10 rounded-lg px-3 py-1.5 text-sm">
              <span className="text-slate-300">Event performance</span>
            </div>
          </div>
          {/* Mock Graph Area */}
          <div className="h-64 flex items-end justify-between space-x-2 relative">
            <div className="absolute inset-0 bg-gradient-to-t from-primary-500/10 to-transparent"></div>
            {[40, 70, 45, 90, 60, 110, 80, 120].map((h, i) => (
              <div key={i} className="w-full relative group h-full flex items-end">
                <div 
                  className="w-full bg-gradient-to-t from-primary-600 to-accent-400 rounded-t-sm opacity-70 group-hover:opacity-100 transition-all duration-300 relative z-10"
                  style={{ height: `${(h / 120) * 100}%` }}
                >
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 w-2 h-2 bg-white rounded-full shadow-[0_0_10px_#fff] opacity-0 group-hover:opacity-100 transition-opacity"></div>
                </div>
                {/* Secondary data point mock */}
                <div 
                  className="absolute bottom-0 w-1/2 left-1/4 bg-primary-500/50 rounded-t-sm z-0"
                  style={{ height: `${(h / 120) * 60}%` }}
                ></div>
              </div>
            ))}
          </div>
          <div className="flex justify-between text-xs text-slate-500 mt-4">
            <span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span><span>Oct</span>
          </div>
        </div>

        <div className="space-y-6">
          <div className="glass-panel p-6 flex items-center space-x-4 h-full">
             <div className="p-3 bg-primary-500/20 rounded-xl text-primary-400">
               <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
             </div>
             <div>
               <p className="text-sm text-slate-400">Total Registrations</p>
               <p className="text-3xl font-bold text-white">2,450</p>
             </div>
          </div>
          <div className="glass-panel p-6 flex items-center space-x-4 h-full">
             <div className="p-3 bg-accent-500/20 rounded-xl text-accent-400">
               <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
             </div>
             <div>
               <p className="text-sm text-slate-400">Total Events</p>
               <p className="text-3xl font-bold text-white">18 <span className="text-xs text-accent-400 ml-1 font-normal">Active</span></p>
             </div>
          </div>
          <div className="glass-panel p-6 flex items-center space-x-4 h-full">
             <div className="p-3 bg-indigo-500/20 rounded-xl text-indigo-400">
               <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
             </div>
             <div>
               <p className="text-sm text-slate-400">Revenue</p>
               <p className="text-3xl font-bold text-white">$35,800</p>
             </div>
          </div>
        </div>
      </div>

      {/* Bottom row: Upcoming Events & Latest Bookings */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="glass-panel p-6">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold text-white">Upcoming Events</h2>
            <button className="neon-button text-xs py-1.5 px-4 rounded md">Create New Event</button>
          </div>
          <div className="grid grid-cols-2 gap-4">
            {[1, 2].map(i => (
              <div key={i} className="bg-white/5 border border-white/10 rounded-xl p-4 hover:bg-white/10 transition group cursor-pointer">
                <div className="h-24 bg-gradient-to-br from-primary-900/50 to-accent-900/50 rounded-lg mb-3 flex items-center justify-center overflow-hidden relative">
                   <div className="absolute inset-0 bg-primary-600/20 group-hover:bg-transparent transition mix-blend-overlay"></div>
                   <span className="text-slate-500 font-medium">Event Cover</span>
                </div>
                <h3 className="text-white font-bold text-lg">Tech Conference 2026</h3>
                <p className="text-xs text-slate-400 flex items-center mt-1">
                   <svg className="w-3 h-3 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                   Nov 14, 2026
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="glass-panel p-6">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold text-white">System Test Module</h2>
          </div>
          {user ? (
            <div className="bg-black/40 border border-white/10 p-6 rounded-xl backdrop-blur-md">
              <h3 className="text-lg font-bold text-white mb-2 flex items-center">
                <span className="w-2 h-2 rounded-full bg-accent-500 mr-2 shadow-[0_0_8px_rgba(236,72,153,0.8)] animate-pulse"></span>
                Realtime Ping Flow
              </h3>
              <p className="text-sm text-slate-400 mb-4 leading-relaxed">
                Initiate a mock vendor dispatch sequence. This module bypasses standard auth matrix to deploy a test entity and issue a booking request. Neural uplink will instantly reflect the notification via payload transmission.
              </p>
              <button onClick={testBooking} className="neon-button w-full text-sm">TRANSMIT TEST BOOKING</button>
              {message && (
                <div className="mt-4 p-3 rounded-lg bg-primary-500/10 border border-primary-500/30 text-center">
                  <p className="text-sm font-medium text-primary-400">{message}</p>
                </div>
              )}
            </div>
          ) : (
            <div className="flex items-center justify-center h-40 text-slate-400">
              <p>Authentication required to access modules.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
